[test]
env = ".env.test"
timeout = 30000
preload = ["./src/test/preload.ts"]
coverageSkipTestFiles = true

# exclude E2E tests and generated files from `bun test`
testIgnorePatterns = ["**/e2e/**", "**/generated/**"]
